osx_image: xcode8.3
sudo: false
env:
  matrix:
  - TRAVIS_NODE_VERSION: '4.2'
  - TRAVIS_NODE_VERSION: '6.11'
git:
  depth: 10
install:
- npm install
script:
- npm test
notifications:
  slack:
    secure: gn0YH0MCFOYR3Dd8Vsx3K/J9G0aazhnRjQVfqbeRKN3f6vToKif1CxhiDLXI6cxEB5DBiAtpK58jkoDYrXoNLGuSbiTHBJ+ankU8aG3s0OTIHa/8I0TjRKjBRc0PrMV7n7EiLC6LQxNe0x0mMSE1gdOUeS1UrZ5ZiVrS1u0eHHs=
