# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm cache clean
  - npm config set registry "http://registry.npmjs.org"
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
